backends/miniaudio: Don't use std::async.
Breaks 32-bit MinGW linking:
/usr/lib/gcc/i686-w64-mingw32/16.0.0/../../../../i686-w64-mingw32/bin/ld: missing --end-group; added as last command line option
/usr/lib/gcc/i686-w64-mingw32/16.0.0/../../../../i686-w64-mingw32/bin/ld: soloud_miniaudio.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZZNSt19_Sp_make_shared_tag5_S_tiEvE5__tag+0x0): multiple definition of `std::_Sp_make_shared_tag::_S_ti()::__tag'; /usr/lib/gcc/i686-w64-mingw32/16.0.0/../../../../i686-w64-mingw32/lib/../lib/libstdc++.a(fs_path.o):/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libstdc++-v3/include/bits/shared_ptr_base.h:571: first defined here

It wasn't doing anything, anyways, since the threading didn't work with WASAPI.